version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: authbase-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: authbase
      MYSQL_USER: authbase_user
      MYSQL_PASSWORD: authbase_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - authbase-network

volumes:
  mysql_data:

networks:
  authbase-network:
    driver: bridge
