spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: false

  # Liquibase Configuration for Testing
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: test

  redis:
    host: localhost
    port: 6379
    database: 1
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

# CORS Configuration for Testing (Minimal)
cors:
  allowed-origin-patterns:
    - "*"
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed-headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
  exposed-headers:
    - "Authorization"
  allow-credentials: true
  max-age: 3600

logging:
  level:
    com.authbase: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
