spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE:authbase}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:authbase_user}
    password: ${MYSQL_PASSWORD:authbase_password}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # Liquibase Configuration for Development
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev
    default-schema: authbase

# CORS Configuration for Development
cors:
  allowed-origin-patterns:
    - "http://localhost:3000" # React default
    - "http://localhost:4200" # Angular default
    - "http://localhost:8080" # Vue default
    - "http://localhost:5173" # Vite default
    - "*" # Allow all for development
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
    - "PATCH"
  allowed-headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
    - "X-Requested-With"
    - "Access-Control-Request-Method"
    - "Access-Control-Request-Headers"
  exposed-headers:
    - "Authorization"
    - "X-Total-Count"
    - "X-Page-Number"
    - "X-Page-Size"
  allow-credentials: true
  max-age: 3600

logging:
  level:
    com.authbase: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
