spring:
  application:
    name: api-auth-base
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

jwt:
  secret: 714171e8028ac915884598667658d6fccbb0a43abb4455d62831c948f628f0744bd2727ba1f5b061c220ba987df8284cde4acc74c3ea32381381b1d5df23e375
  access-token-expiration: 900000 # 15 minutes in milliseconds
  refresh-token-expiration: 604800000 # 7 days in milliseconds

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

auth:
  redis:
    enabled: true
    token-blacklist-prefix: "blacklist:"
  logout:
    blacklist-access-tokens: true
    remove-refresh-tokens: true
    log-events: true

# Whitelist endpoints configuration
# These endpoints are publicly accessible without authentication
security:
  whitelist:
    endpoints:
      # Authentication endpoints (public)
      - "/api/auth/**"

      # Health check endpoints (public)
      - "/api/health/**"
      - "/health/**"

      # API Documentation endpoints (public)
      - "/api/swagger-ui.html"
      - "/api/api-docs/**"
      - "/api/api-docs"
      - "/swagger-ui/**"
      - "/swagger-ui.html"
      - "/api-docs/**"
      - "/api-docs"

      # Actuator endpoints (public)
      - "/actuator/**"

      # Static resources (public)
      - "/static/**"
      - "/css/**"
      - "/js/**"
      - "/images/**"
      - "/favicon.ico"

      # Error pages (public)
      - "/error"

      # Root endpoint (public)
      - "/"
      # OPTIONS requests for CORS preflight (public)
      - "/**"
